#include "cgmres_initializer/d_cgmres_initializer.h"

#include "cgmres_initializer/d_mfgmres_for_cgmres_initializer.h"
#include "cgmres_initializer/d_inexact_newton_for_zero_horizon_ocp.h"
#include "common/d_memory_manager.h"
#include "common/d_linear_algebra.h"


#define REAL double

#define CGMRES_INITIALIZER_STRSIZE d_cgmres_initializer_strsize
#define CGMRES_INITIALIZER_MEMSIZE d_cgmres_initializer_memsize
#define CGMRES_INITIALIZER_CREATE d_cgmres_initializer_create
#define CGMRES_INITIALIZER_DELETE d_cgmres_initializer_delete
#define CGMRES_INITIALIZER_SET_TERMINATION_CRITERIONS d_cgmres_initializer_set_termination_criterions
#define CGMRES_INITIALIZER_SET_INITIAL_GUESS_SOLUTION d_cgmres_initializer_set_initial_guess_solution
#define CGMRES_INITIALIZER_COMPUTE_INITIAL_SOLUTION d_cgmres_initializer_compute_initial_solution
#define CGMRES_INITIALIZER_GET_TERMINAL_COST_DERIVATIVE d_cgmres_initializer_get_terminal_cost_derivative
#define CGMRES_INITIALIZER d_cgmres_initializer

#define MFGMRES_FOR_CGMRES_INITIALIZER_MEMSIZE d_mfgmres_for_cgmres_initializer_memsize
#define MFGMRES_FOR_CGMRES_INITIALIZER_CREATE d_mfgmres_for_cgmres_initializer_create
#define MFGMRES_FOR_CGMRES_INITIALIZER_DELETE d_mfgmres_for_cgmres_initializer_delete
#define MFGMRES_FOR_CGMRES_INITIALIZER_SOLVE_LINEAR_PROBLEM d_mfgmres_for_cgmres_initializer_solve_linear_problem

#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_MEMSIZE d_inexact_newton_for_zero_horizon_ocp_memsize
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_CREATE d_inexact_newton_for_zero_horizon_ocp_create
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DELETE d_inexact_newton_for_zero_horizon_ocp_delete
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_GET_ERROR_NORM d_inexact_newton_for_zero_horizon_ocp_get_error_norm
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_GET_TERMINAL_COST_DERIVATIVE d_inexact_newton_for_zero_horizon_ocp_get_terminal_cost_derivative
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DIMX d_inexact_newton_for_zero_horizon_ocp_dimx
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DIMU d_inexact_newton_for_zero_horizon_ocp_dimu
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DIMC d_inexact_newton_for_zero_horizon_ocp_dimc

#define ALLOCATE_VEC allocate_dvec
#define FREE_VEC free_dvec

#define VECCP cgmres_dveccp
#define VECAD cgmres_dvecadd


#include "x_cgmres_initializer.c"