#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include "cgmres_initializer/d_inexact_newton_for_zero_horizon_ocp.h"
#include "common/d_memory_manager.h"
#include "common/d_linear_algebra.h"


#define REAL double

#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_STRSIZE d_inexact_newton_for_zero_horizon_ocp_strsize
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_MEMSIZE d_inexact_newton_for_zero_horizon_ocp_memsize
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_CREATE d_inexact_newton_for_zero_horizon_ocp_create
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DELETE d_inexact_newton_for_zero_horizon_ocp_delete
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_COMPUTE_B d_inexact_newton_for_zero_horizon_ocp_compute_b
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_COMPUTE_AX d_inexact_newton_for_zero_horizon_ocp_compute_ax
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_GET_ERROR_NORM d_inexact_newton_for_zero_horizon_ocp_get_error_norm
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_GET_TERMINAL_COST_DERIVATIVE d_inexact_newton_for_zero_horizon_ocp_get_terminal_cost_derivative
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DIMX d_inexact_newton_for_zero_horizon_ocp_dimx
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DIMU d_inexact_newton_for_zero_horizon_ocp_dimu
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_DIMC d_inexact_newton_for_zero_horizon_ocp_dimc

#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP_MFGMRES_ARGS d_inexact_newton_for_zero_horizon_ocp_mfgmres_args
#define INEXACT_NEWTON_FOR_ZERO_HORIZON_OCP d_inexact_newton_for_zero_horizon_ocp

#define ZERO_HORIZON_OCP_STRSIZE d_zero_horizon_ocp_strsize 
#define ZERO_HORIZON_OCP_MEMSIZE d_zero_horizon_ocp_memsize
#define ZERO_HORIZON_OCP_CREATE d_zero_horizon_ocp_create
#define ZERO_HORIZON_OCP_DELETE d_zero_horizon_ocp_delete
#define ZERO_HORIZON_OCP_COMPUTE_OPTIMALITY_RESIDUAL d_zero_horizon_ocp_compute_optimality_residual
#define ZERO_HORIZON_OCP_COMPUTE_TERMINAL_COST_DERIVATIVE d_zero_horizon_ocp_compute_terminal_cost_derivative
#define ZERO_HORIZON_OCP_DIMX d_zero_horizon_ocp_dimx
#define ZERO_HORIZON_OCP_DIMU d_zero_horizon_ocp_dimu
#define ZERO_HORIZON_OCP_DIMC d_zero_horizon_ocp_dimc

#define ALLOCATE_VEC allocate_dvec
#define FREE_VEC free_dvec

#define VECNRM2 cgmres_dvecnrm2
#define AXPY cgmres_daxpy
#define AXPBY cgmres_daxpby


#include "x_inexact_newton_for_zero_horizon_ocp.c"