#include "s_zero_horizon_ocp.h"
#include "s_memory_manager.h"


#define REAL float

#define ZERO_HORIZON_OCP_STRSIZE s_zero_horizon_ocp_strsize
#define ZERO_HORIZON_OCP_MEMSIZE s_zero_horizon_ocp_memsize
#define ZERO_HORIZON_OCP_CREATE s_zero_horizon_ocp_create
#define ZERO_HORIZON_OCP_DELETE s_zero_horizon_ocp_delete
#define ZERO_HORIZON_OCP_COMPUTE_OPTIMALITY_RESIDUAL s_zero_horizon_ocp_compute_optimality_residual
#define ZERO_HORIZON_OCP_COMPUTE_TERMINAL_COST_DERIVATIVE s_zero_horizon_ocp_compute_terminal_cost_derivative
#define ZERO_HORIZON_OCP_DIMX s_zero_horizon_ocp_dimx
#define ZERO_HORIZON_OCP_DIMU s_zero_horizon_ocp_dimu
#define ZERO_HORIZON_OCP_DIMC s_zero_horizon_ocp_dimc
#define ZERO_HORIZON_OCP s_zero_horizon_ocp

#define ALLOCATE_VEC allocate_svec
#define FREE_VEC free_svec

#define NMPC_MODEL_CREATE s_nmpc_model_create
#define NMPC_MODEL_PHIX s_nmpc_model_phix
#define NMPC_MODEL_HU s_nmpc_model_hu
#define NMPC_MODEL_DIMX s_nmpc_model_dimx
#define NMPC_MODEL_DIMU s_nmpc_model_dimu
#define NMPC_MODEL_DIMC s_nmpc_model_dimc
#define NMPC_MODEL s_nmpc_model


#include "x_zero_horizon_ocp.c"