#include "d_single_shooting_cgmres.h"

#include "d_mfgmres_for_single_shooting_cgmres.h"
#include "d_single_shooting_continuation.h"
#include "d_single_shooting_continuation_mfgmres_args.h"
#include "d_linear_algebra.h"
#include "d_memory_manager.h"


#define REAL double

#define SINGLE_SHOOTING_CGMRES_STRSIZE d_single_shooting_cgmres_strsize
#define SINGLE_SHOOTING_CGMRES_MEMSIZE d_single_shooting_cgmres_memsize
#define SINGLE_SHOOTING_CGMRES_CREATE d_single_shooting_cgmres_create
#define SINGLE_SHOOTING_CGMRES_DELETE d_single_shooting_cgmres_delete
#define SINGLE_SHOOTING_CGMRES_SET_INITIALIZATION_PARAMETERS d_single_shooting_cgmres_set_initialization_parameters
#define SINGLE_SHOOTING_CGMRES_INITIALIZE_SOLUTION d_single_shooting_cgmres_initialize_solution
#define SINGLE_SHOOTING_CGMRES_UPDATE_CONTROL_INPUT d_single_shooting_cgmres_update_control_input
#define SINGLE_SHOOTING_CGMRES_GET_CONTROL_INPUT d_single_shooting_cgmres_get_control_input
#define SINGLE_SHOOTING_CGMRES_GET_ERROR_NORM d_single_shooting_cgmres_get_error_norm
#define SINGLE_SHOOTING_CGMRES d_single_shooting_cgmres

#define SINGLE_SHOOTING_CONTINUATION_MEMSIZE d_single_shooting_continuation_memsize
#define SINGLE_SHOOTING_CONTINUATION_CREATE d_single_shooting_continuation_create
#define SINGLE_SHOOTING_CONTINUATION_DELETE d_single_shooting_continuation_delete
#define SINGLE_SHOOTING_CONTINUATION_INTEGRATE_SOLUTION d_single_shooting_continuation_integrate_solution
#define SINGLE_SHOOTING_CONTINUATION_GET_ERROR_NORM d_single_shooting_continuation_get_error_norm
#define SINGLE_SHOOTING_CONTINUATION_RESET_HORIZON_LENGTH d_single_shooting_continuation_reset_horizon_length
#define SINGLE_SHOOTING_CONTINUATION_DIMX d_single_shooting_continuation_dimx
#define SINGLE_SHOOTING_CONTINUATION_DIMU d_single_shooting_continuation_dimu
#define SINGLE_SHOOTING_CONTINUATION_DIMC d_single_shooting_continuation_dimc

#define MFGMRES_FOR_SINGLE_SHOOTING_CGMRES_MEMSIZE d_mfgmres_for_single_shooting_cgmres_memsize
#define MFGMRES_FOR_SINGLE_SHOOTING_CGMRES_CREATE d_mfgmres_for_single_shooting_cgmres_create
#define MFGMRES_FOR_SINGLE_SHOOTING_CGMRES_DELETE d_mfgmres_for_single_shooting_cgmres_delete
#define MFGMRES_FOR_SINGLE_SHOOTING_CGMRES_SOLVE_LINEAR_PROBLEM d_mfgmres_for_single_shooting_cgmres_solve_linear_problem

#define CGMRES_INITIALIZER_MEMSIZE d_cgmres_initializer_memsize
#define CGMRES_INITIALIZER_CREATE d_cgmres_initializer_create
#define CGMRES_INITIALIZER_DELETE d_cgmres_initializer_delete
#define CGMRES_INITIALIZER_SET_TERMINATION_CRITERIONS d_cgmres_initializer_set_termination_criterions
#define CGMRES_INITIALIZER_SET_INITIAL_GUESS_SOLUTION d_cgmres_initializer_set_initial_guess_solution
#define CGMRES_INITIALIZER_COMPUTE_INITIAL_SOLUTION d_cgmres_initializer_compute_initial_solution

#define VECCP hpcgmres_dveccp

#define ALLOCATE_VEC allocate_dvec
#define FREE_VEC free_dvec


#include "x_single_shooting_cgmres.c"