#include <stdlib.h>
#include <stdio.h>
#include <cmath.h>

#include <blasfeo.h>

#include "s_single_shooting_cgmres.h"


#define REAL float 

#define SINGLE_SHOOTING_CGMRES s_single_shooting_cgmres
#define SINGLE_SHOOTING_CGMRES_STRSIZE s_single_shooting_cgmres_strsize
#define SINGLE_SHOOTING_CGMRES_MEMSIZE s_single_shooting_cgmres_memsize
#define SINGLE_SHOOTING_CGMRES_CREATE s_single_shooting_cgmres_create
#define SINGLE_SHOOTING_CGMRES_SET_INITIALIZATION_PARAMETERS s_single_shooting_cgmres_set_initialization_parameters
#define SINGLE_SHOOTING_CGMRES_INITIALIZE_SOLUTION s_single_shooting_cgmres_initialize_solution
#define SINGLE_SHOOTING_CGMRES_UPDATE_CONTROL_INPUT s_single_shooting_cgmres_update_control_input
#define SINGLE_SHOOTING_CGMRES_GET_CONTROL_INPUT s_single_shooting_cgmres_get_control_input
#define SINGLE_SHOOTING_CGMRES_GET_ERROR_NORM s_single_shooting_cgmres_get_error_norm

#define SINGLE_SHOOTING_CONTINUATION_MEMSIZE s_single_shooting_continuation_memsize
#define SINGLE_SHOOTING_CONTINUATION_CREATE s_single_shooting_continuation_create
#define SINGLE_SHOOTING_CONTINUATION_INTEGRATE_SOLUTION s_single_shooting_continuation_integrate_solution
#define SINGLE_SHOOTING_CONTINUATION_GET_ERROR_NORM s_single_shooting_continuation_get_error_norm
#define SINGLE_SHOOTING_CONTINUATION_RESET_HORIZON_LENGTH s_single_shooting_continuation_reset_horizon_length

#define MFGMRES_MEMSIZE s_mfgmres_for_single_shooting_cgmres_memsize
#define MFGMRES_CREATE s_mfgmres_for_single_shooting_cgmres_create
#define MFGMRES_SOLVE_LINEAR_PROBLEM s_mfgmres_for_single_shooting_cgmres_solve_linear_problem

#define CGMRES_INITIALIZER_MEMSIZE s_cgmres_initializer_memsize
#define CGMRES_INITIALIZER_CREATE s_cgmres_initializer_create
#define CGMRES_INITIALIZER_SET_TERMINATION_CRITERIONS s_cgmres_initializer_set_termination_criterions
#define CGMRES_INITIALIZER_SET_INITIAL_GUESS_SOLUTION s_cgmres_initializer_set_initial_guess_solution
#define CGMRES_INITIALIZER_COMPUTE_INITIAL_SOLUTION s_cgmres_initializer_compute_initial_solution

#define STRVEC blasfeo_svec
#define SIZE_STRVEC blasfeo_memsize_svec
#define CREATE_STRVEC blasfeo_memsize_svec

#define VECCSE blasfeo_svecse
#define VECCP blasfeo_sveccp


#include "x_single_shooting_cgmres.c"