#include "common/d_time_varying_smooth_horizon.h"

#include <math.h>


#define REAL double

#define TIME_VARYING_SMOOTH_HORIZON d_time_varying_smooth_horizon

#define TIME_VARYING_SMOOTH_HORIZON_STRSIZE d_time_varying_smooth_horizon_strsize
#define TIME_VARYING_SMOOTH_HORIZON_CREATE d_time_varying_smooth_horizon_create
#define TIME_VARYING_SMOOTH_HORIZON_GET_LENGTH d_time_varying_smooth_horizon_get_length
#define TIME_VARYING_SMOOTH_HORIZON_RESET_LENGTH d_time_varying_smooth_horizon_reset_length


#include "x_time_varying_smooth_horizon.c"