#include "s_time_varying_smooth_horizon.h"


#define REAL float

#define TIME_VARYING_SMOOTH_HORIZON s_time_varying_smooth_horizon

#define TIME_VARYING_SMOOTH_HORIZON_STRSIZE s_time_varying_smooth_horizon_strsize
#define TIME_VARYING_SMOOTH_HORIZON_CREATE s_time_varying_smooth_horizon_create
#define TIME_VARYING_SMOOTH_HORIZON_GET_LENGTH s_time_varying_smooth_horizon_get_length
#define TIME_VARYING_SMOOTH_HORIZON_RESET_LENGTH s_time_varying_smooth_horizon_reset_length


#include "x_time_varying_smooth_horizon.c"